version: '2'
networks:
  shared:
    external:
      name: shared
services:
  database:
    networks:
      - shared
    image: mysql:8.0
    container_name: demo-db
    ports:
      - 3306:3306
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo